language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: n5UyZDMLBtRVSAy9sA5XqkFTnolKYe/p5kXCxNqto38l7LYresk2hDhvCPpbkH73Xh7WbAZf+opDf/5D4zvZBaeDB+VXhZwwOsdcT3zDw1cQ1Qa6UW+XWbtl6j5Z15IxPis0+fPYKVBKSoPFocPmK0eAZdvvhmnjTQCV5zcBewgCHNvhsqOFiz9VWZTuVi6JWaaOLoAtgFXXLLSwL1TzcGUOvJYDGfYc0Dt3BtzT7zII5aFHqV9eRj6I6BfyhLJNJJFZm1PegHCis8dhxdjEUR6brBt2Oe3/qNdtEZ70sMGi4pv1em+LEBCdKFkUMk/8gHNNipUgkuYK9i4CgpMHDMUWCPr0W82fwfgBgdeejGG4uMHGzAA0VK9yM4lbhphnL9CyAefB1WwIZhTeffpP9+bZVTse5Eiy6sx3DqdTndy3IrXFriRlSV2n6fKl1H+9M1vCgP03ITcOL89ofzbaQnDz4CJ0UfZFxWtPrCMzOQ+Q6lhH5UU7SYJw8sgw9JpkYD6CFfnZfyuvDm0JoLfSxMdM5N5cfeKc8lX0SZAIuKUbbpthPbl/6ZPK5X0huAvPNJkNHzZdxb09wAEHHVZ7rQhM8rcwdny7EOVFOz2gAIifw8yBHE8DIJXZt1xSBX0QcdhHEFsfMCBIDXYxn0YEqASjCUKAPWQG80A6Enn6upE=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: Zw3oyxyZYtE7VP/wMo0MZtGo1MsxxP8YM5HPQFMaRTyDlzGx6QqQck0HeUQWbYag8QmL96IWnUsF/wfTb9nNXm9UOOpd6/KCXiEjQntfEIIPstzEslMpYrAqHBIk5ovU1SzzzzmpuRvJtgxv/p0+Wnv5T6X57rweFOZ+u7k6QRsJqYzww5qGeajYWvZDJOPX4xSKAxnq7shszAFYm4wkUSkD5SLKnQaJlgxWiPJfgo4o4AyrFy2vRViDkUtfKD/JsIAQ2YCt/7zpoWKCHj6zAI3gTUUYwVZ63C2t6dhpBxf4lKl1Anweq8cXY8g70nLFFAKfShFFymmD8KuSoetvi1dMEpo/96XiD+hTg2F2RdAVAvaHFd8ozppNPIZKa5vIGEkkJrYGP85xHjmCt2PCJBDVknYaChVceoubgBULeC2ABHRH4+6BCxHWnNJRta8WvWs4h6pnb78FRM3PcL7tMeDh8roKaqKv/ECIxBKdJj/MFJsgI4gaTFa+8bABdKnBZEl+ifaFk0t39NXWeEwLFoIn0c+s9gAttvnaMgo52iIgbPW2HiiS7wFghL4JJDsaIYcRFrn4CF92PDVNrZFIWS3RbfcUD31yEMt+GLq9Pe8F+TD4xmK9V/hyamZTaE7a70GXwa847BoHB8MbJSZm0iESsnbUnJLqyrgKuaM4X1k=
  - secure: SEJ9b59WPc5etNl45RnQkYvUGLmtuYblAJTE+5GUcF3gLGpneJ48t5s6ERdswJszkmdys8qoxnb9pX5km2qJkGSIBvn3bkzknwaLEoc87Y/3qpyLdQMgrP7MwJyxi4qgDJZ6eLT7w4QGl1RGDTu++tnLEqPGVvyV8CEStGaeQlqjD/NvDodYIuO/eCj8Gbvcqq+lj6GFufvduixLeELLl1jxglH48tWn6b/6hPXCSIMxh/9QZd2+0qqfrAt7MWwcxl5IQAq3rbA+UZ40Dh7//dc9Bqv9qpUk6fcI0lbyS9mPaC7ejQE2oZL1IEUO7yq1ZUJ6ofZtiwzbztJqIZJjHB/wFjsSGYKTUIldvDhf+4Ty46qTXynjBwFRk/A4ZAqIpaBjH8f5pA4oiAuFDGkX4nfdSPZCUTMR8rMAQNEvoBfoi3KPZ03oXy7LoJ0fwEBVwbtoHbdNgbABkmNxc9fQLjH5kNSiUCZPprBmg4HEJNWPU/ancN0bwFszyjnTJlaWk75GvMFwZoVHt72IUQO1oeiwX7cCT4YeZRvICceuWGF/YZ1DdOOiun1MMFuoQvhfG5kk0w3Q775mah3GbsbjEtDUpPBXbGYyBIIPzZ/0fbLQVP0qcwuK/ENdDFSd6VFfBevQUof9mjP+GjSxABzicC10Aftw8r/6HHDEa/svl2s=
  - secure: Go0UTeHRYJu2b0oQap66nUyPR4gkgqBZ3oXzDrGO3snZxvMlxcgNdAc+mP0C63AULDEiVuracclg/vO2rLbviq2kQCZxb1lBMpyZls8PbnWNczmFbUWJ1UcQD/wgF2kyxqTYxXha8pHPJkNPzBORDF4mp4rAwFaD3dxSu0Pt386jqG9gqxnig2bGCTwdPMQWbDDXV3ouyNeRL3pvsxjsnc+lOxbCcRmIwZoInAFghjcaAPZA5U9F62uSgT4Fpkp4i9iA8QXsrr2XE9eMo2brYgPffKe64nGHVA8pgl8PBKk3OTVKVZoKYaSW3A1X93defeQV0S8XcJhEJaT52UJqq4HfY+ZvCE7jHv2VR0SVDDvC0GPk4TbYq/rDTOJ2fEDUniwkH/JUJZvVEVuDBv3uxWeQzZ30pOYEh4UdNVE3Hfv/hyVHUS6vazs0aPAtI7s73245lFdv0rZ9cYK9F0kvmh4s7hVb2Z0OMQ7lmtjjtXSMidb1/Z/OQkIiwXufQ17vkAWrVfIPUD5qRLw4GYUN29JSqd06NHfWUsj/Q0nQvuKo8fYlcZV5P7UbRGoH9D4CAzZF6JOKNJCoz6EAaiBDM5RJDzpstx+dsOYaRsRvXNX68IXSt/vSL3SPF1f2FgrFGaPQfqe+lznMsD3tRz/UAYy3qlXnMykiKVFMJXT2t3U=
before_install:
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=sub-dog-daemon-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_HOME}/lof-ws-test-5c33f02ea8c8.json
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
